language: java
jdk:
  - openjdk11
install:
  - sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
  - sudo apt-get install --reinstall ttf-mscorefonts-installer
script: mvn clean install
